version: "3"
services:
    server:
        image: api
        restart: always
        ports: 
            - 8080:80
        depends_on: 
            - mongo
    
    client:
        image: client
        restart: always
        ports:
            - 2368:2368
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
